# Generated by Django 3.2.3 on 2021-06-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3cut', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='audio')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
